# fly.toml app configuration file generated for insignia-notify on 2023-10-06T10:55:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "insignia-notify"
primary_region = "atl"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "insignia-notify.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
